apiVersion: v1
kind: Service
metadata:
  name: demo-frontend
  namespace: argo
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: "/"
  labels:
    env: dev
spec:
  selector:
    app: frontend-fargate
