apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-frontend
  namespace: argo
  labels:
    env: dev
    duck: test
spec:
  selector:
    matchLabels:
      app: frontend-fargate
  template:
    metadata:
      labels:
        app: frontend-fargate
