apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 311724524637.dkr.ecr.ap-northeast-2.amazonaws.com/argo-front
  newName: 311724524637.dkr.ecr.ap-northeast-2.amazonaws.com/argo-front
  newTag: b78587b5
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
